services:
  mysql:
    image: mysql:8.0  # MySQL로 변경!
    container_name: user-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: userService
      MYSQL_PASSWORD: pwmUser5921
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  user-service:
    image: pwm-user-service:latest
    container_name: pwm-user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: userService
      SPRING_DATASOURCE_PASSWORD: pwmUser5921
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: 0
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
