version: '3.8'
services:
  mysql:
    image: mariadb:latest
    container_name: mysql-user
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: userService
      MYSQL_PASSWORD: pwmUser5921
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    image: pwm-user-service:latest
    container_name: pwm-user-service
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_USERNAME: userService
      DB_PASSWORD: pwmUser5921
    depends_on:
      mysql:
        condition: service_healthy